### PR TITLE
Fix remove-ember-data-is-new-serializer-api.

### LINKED ISSUE #97: Command remove-ember-data-is-new-serializer-api is invalid.
In latest stable version (0.8.1), running the example of the readme fails. The command cannot be found.

```
$ ember watson:remove-ember-data-is-new-serializer-api app/
The specified command watson:remove-ember-data-is-new-serializer-api is invalid. For available options, see `ember help`.
```

### PR DESCRIPTION
**Pull request by abuiles**
Fixes #97

### CODE REVIEW

File: lib/commands/index.js [hunk 1]
```diff
@@ -10,5 +10,6 @@ module.exports = {
   'watson:convert-resource-router-mapping': require('./convert-resource-router-mapping'),
   'watson:find-overloaded-cps': require('./find-overloaded-cps'),
   'watson:use-destroy-app-helper': require('./use-destroy-app-helper'),
-  'watson:replace-needs-with-injection': require('./replace-needs-with-injection')
+  'watson:replace-needs-with-injection': require('./replace-needs-with-injection'),
+  'watson:remove-ember-data-is-new-serializer-api': require('./remove-ember-data-is-new-serializer-api')
```
Comment (abuiles) [inline lib/commands/index.js]: @fivetanley I totally forgot to check this :)
